service: kpi-schedule-etl-steps
app: kpi-schedule
frameworkVersion: '3'

plugins:
  - serverless-step-functions
  - serverless-plugin-log-retention

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: dotnet6
  region: eu-central-1
  memorySize: 512
  timeout: 900
  # Lambda function's IAM Role
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:*"
          Resource: "arn:aws:dynamodb:${self:provider.region}:${self:custom.account}:table/KpiSchedule*"

custom:
  account: 251999958052
  logRetentionInDays: 30

# Service wide environment variables
environment:
  
package:
  artifact: bin/deploy-package.zip

functions: 
  roz-kpi-group-schedules-etl:
    handler: KpiSchedule.EtlStepFunction::KpiSchedule.EtlStepFunction.SchedulesEtlTasks::RozKpiGroupSchedulesEtlTask
    
  roz-kpi-teacher-schedules-etl:
    handler: KpiSchedule.EtlStepFunction::KpiSchedule.EtlStepFunction.SchedulesEtlTasks::RozKpiTeacherSchedulesEtlTask

stepFunctions:
  stateMachines:
    KpiScheduleEtlSteps:
      definition:
        StartAt: Parallel
        States:
          Parallel:
            Type: Parallel
            End: true
            Branches:
            - StartAt: Extract Group Schedules from roz.kpi.ua
              States:
                Extract Group Schedules from roz.kpi.ua:
                  Type: Task
                  Resource: arn:aws:states:::lambda:invoke
                  OutputPath: "$.Payload"
                  Parameters:
                    FunctionName: arn:aws:lambda:${self:provider.region}:${self:custom.account}:function:${self:service}-${self:provider.stage}-roz-kpi-group-schedules-etl:$LATEST
                    Payload.$: $
                  Retry:
                  - ErrorEquals:
                    - Lambda.ServiceException
                    - Lambda.AWSLambdaException
                    - Lambda.SdkClientException
                    - Lambda.TooManyRequestsException
                    IntervalSeconds: 2
                    MaxAttempts: 6
                    BackoffRate: 2
                  - ErrorEquals: [TaskCanceledException]
                    BackoffRate: 2
                    IntervalSeconds: 10
                    MaxAttempts: 5
                    Comment: Retry on timeout from roz.kpi.ua
                  End: true
            - StartAt: Extract Teacher Schedules from roz.kpi.ua
              States:
                Extract Teacher Schedules from roz.kpi.ua:
                  Type: Task
                  Resource: arn:aws:states:::lambda:invoke
                  OutputPath: "$.Payload"
                  Parameters:
                    FunctionName: arn:aws:lambda:${self:provider.region}:${self:custom.account}:function:${self:service}-${self:provider.stage}-roz-kpi-teacher-schedules-etl:$LATEST
                    Payload.$: $
                  Retry:
                  - ErrorEquals:
                    - Lambda.ServiceException
                    - Lambda.AWSLambdaException
                    - Lambda.SdkClientException
                    - Lambda.TooManyRequestsException
                    IntervalSeconds: 2
                    MaxAttempts: 6
                    BackoffRate: 2
                  - ErrorEquals: [TaskCanceledException]
                    BackoffRate: 2
                    IntervalSeconds: 10
                    MaxAttempts: 5
                    Comment: Retry on timeout from roz.kpi.ua
                  End: true
    
    
resources:
  Resources:
    GroupSchedulesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: GroupName
          AttributeType: S
        - AttributeName: ScheduleId
          AttributeType: S
        TableName: KpiSchedule-GroupSchedules
        KeySchema:
        - AttributeName: ScheduleId
          KeyType: HASH
        GlobalSecondaryIndexes:
        - IndexName: GroupName-index
          KeySchema:
          - AttributeName: GroupName
            KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
        BillingMode: PAY_PER_REQUEST

    TeacherSchedulesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: TeacherName
          AttributeType: S
        - AttributeName: ScheduleId
          AttributeType: S
        TableName: KpiSchedule-TeacherSchedules
        KeySchema:
        - AttributeName: ScheduleId
          KeyType: HASH
        GlobalSecondaryIndexes:
        - IndexName: TeacherName-index
          KeySchema:
          - AttributeName: TeacherName
            KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
        BillingMode: PAY_PER_REQUEST

    StudentSchedulesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: OwnerId
          AttributeType: S
        - AttributeName: ScheduleId
          AttributeType: S
        TableName: KpiSchedule-StudentSchedules
        KeySchema:
        - AttributeName: OwnerId
          KeyType: HASH
        - AttributeName: ScheduleId
          KeyType: RANGE
        BillingMode: PAY_PER_REQUEST