name: Deploy serverless to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x  
        
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install AWS Lambda tools for dotnet CLI
      run: dotnet tool install -g Amazon.Lambda.Tools
      
    - name: Build deployment package
      run: cd ./KpiSchedule.EtlStepFunction && dotnet lambda package -c Release -f net6.0 -o bin/deploy-package.zip
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: arn:aws:iam::251999958052:role/kpi-schedule-github-actions-role
        aws-region: eu-central-1
    
    - name: serverless deploy
      uses: serverless/github-action@v3.1
      with:
        args: |
          -c 
          "cd ./KpiSchedule.EtlStepFunction &&
          serverless plugin install -n serverless-step-functions &&
          serverless plugin install -n serverless-plugin-log-retention &&
          serverless plugin install -n serverless-prune-plugin &&
          serverless deploy"
        entrypoint: /bin/sh
